= Resumé
Cláudio Luís Marques Sampaio, MSc.
v0.99.3, 1/10/2017
:updated: 2017-11-18
:Author: Cláudio Luís Marques Sampaio, MSc.
:Email: patola@makerlinux.com.br
:Date: 17/10/2017
:Revision: v0.1
:doctype: article
:producer: Asciidoctor
:keywords: resume
:reproducible: yes
:icons: font
:lang: en-US
:toclevels: 5
:ascii-ids:
:showcomments:
:stem: latexmath
:math:
:mathematical-format: png
:gitrepo: https://github.com/Patola/resume
:copyright: MIT License
:text-alignment: justify
:source-highlighter: rouge
:imagesdir: imagens
:imagesoutdir: img
:version-pt-br: https://github.com/Patola/resume/blob/master/resume-pt-br.asciidoc
:version-en-us: https://github.com/Patola/resume/blob/master/README.asciidoc

=== Cláudio Luís Marques Sampaio
Rua Benedito da Silva 291 +
Residencial Terra Nova, Campinas, SP +
CEP 13082-694 +
+55 (19) 3289-0644 +
+55 (19) 99116-3949 +
Nationality: *Brazilian* and *Portuguese* (with up to date documents and passports for both) +

Small business: MakerLinux S/A +
CNPJ 21.004.886/0001-11 +
Inscrição Municipal 00311816-9

mailto:patola@gmail.com[personal email] +
mailto:patola@makerlinux.com.br[professional email] +
https://github.com/Patola[github] +
https://linkedin.com/in/patola[linkedin] +
http://buscatextual.cnpq.br/buscatextual/visualizacv.do?id=K4763932Z5[lattes]

{version-pt-br}[brazilian portuguese version of this document]

[[summary]]
==== Summary
* Versatile **system administrator** and **developer** with decades of UNIX and Linux experience in big customers with mission critical environments, working with servers, desktops, mobile and embedded devices.
* Language generalist with programming experience (complete application writing) in C, C++, Java, perl, python, SQL, php and shell scripting.
* Good knowledge on **revision control systems** like **git**, RCS, CVS, bazaar.
* Deep understanding of **open-source licenses**, philosophy and legislation and active contributor of open-source projects.
* Knowledge and experience in packaging software applications in formats like deb, rpm, lpp (AIX), AppImage and snap.
* Good knowledge of **electronics and circuitry** and deep knowledge and understanding of low-cost **3D printing**, with a popular open-source https://github.com/Patola/ebook[book] (in brazilian portuguese) published about it. Due to that, good modelling experience in open-source 3D modellers like Blender, FreeCAD and OpenSCAD.
* Knowledge and practice with **development boards** like ODROIDs from hardkernel, PCDuino, Orange and Banana Pi, Beaglebone Black, Wandboard, Cubieboard and many others.
* Additional knowledge about physics, chemistry, molecular biology and genetics, with a masters degree of genetics and molecular biology from one of Brazil's most respected universities.
* **Public speaker** in a number of http://buscatextual.cnpq.br/buscatextual/visualizacv.do?id=K4763932Z5[high-profile events and conferences], and also **youtube educator** with Maker/3DPrinting channels in https://www.youtube.com/makerlinux[brazilian portuguese] and https://www.youtube.com/channel/UC65ISAck97KwTJRlFHEvTOg[english].

[[objective]]
==== Objective
* Mostly due to my diverse set of abilities, my best performance is at **medium to long term projects with high stakes** and responsibilities and unforeseen circumstances.
* I thrive at **complex systems environments** with multiple languages, being able to learn a new one in a very short time. High skill in troubleshooting and fixing system problems and keep things working even in emergencies.
* With my education experience, I am also very good and **documenting and organizing** computing environments.
* I can administrate diverse **UNIX system environments** including planning for high availability (certified in HACMP for AIX and with experience in other HA systems) and network topology and firewalls.
* I can **code applications** that complement a diverse environment, with scripting, VM-based or compiled languages.
* I can advise on open-source licensing and strategies.
* I can use my extra skills to complement work, e.g. 3D printing for embedded devices or 3D modelling.
* I can work night shift if needed. Had a 5 years period at IBM with that.

[[education]]
==== Education
* State University of Campinas (Unicamp), 2001. Computer engineering.
* State University of Campinas (Unicamp), 2010. Master in Genetics and Molecular Biology.
* Several certifications from Unixes:
** SAIR Linux certification, 2001
** CATE (Certified Advanced Techical Expert) for AIX, 2001.
** HP-UX and Solaris System Administrator certifications.
* Many in-job courses and certifications, from *ITILv3* to individual products like Lotus Notes and Maximo.
* Embedded development courses with __Embedded Labworks__ and (now extinct) __Techtraining__.

[[experience]]
==== Experience
* *Solvo* S/A, 1998-2001: Unix systems administrator, 2001-2002: Unix Application Developer.
* *YMF* S/A, 2002-2003: J2EE developer for financial systems.
* **Convergys, Inc.**, 2003-2005: Unix and Windows applications developer (front-end and backend)
* **IBM Brasil S/A**, 2005-2016: UNIX Systems administrator, Unix Team Lead, Unix Application Developer.

[[languages]]
==== Languages
* **English**: fluent (writing, reading), good (speaking).
* **Portuguese**: native language.
* **French**: intermediate (reading, speaking), basic (writing)
* **Spanish**: intermediate (reading, speaking), basic (writing)

