= Curriculum vitae
Cláudio Luís Marques Sampaio, MSc.
v0.99.4, 23/Dec/2010
:updated: 2017-11-18
:Author: Cláudio Luís Marques Sampaio, MSc.
:Email: patola@makerlinux.com.br
:Date: 17/10/2017
:Revision: v0.1
:doctype: article
:producer: Asciidoctor
:keywords: resume
:reproducible: yes
:icons: font
:lang: pt-BR
:toc-title: Índice
:caution-caption: Cuidado
:important-caption: Importante
:note-caption: Nota
:tip-caption: Dica
:warning-caption: Atenção
:appendix-caption: Apêndice
:example-caption: Exemplo
:figure-caption: Figura
:table-caption: Tabela
:toclevels: 5
:ascii-ids:
:showcomments:
:stem: latexmath
:math:
:mathematical-format: png
:gitrepo: https://github.com/Patola/resume
:copyright: MIT License
:text-alignment: justify
:source-highlighter: rouge
:imagesdir: imagens
:imagesoutdir: img
:version-pt-br: https://github.com/Patola/resume/blob/master/resume-pt-br.asciidoc
:version-en-us: https://github.com/Patola/resume/blob/master/README.asciidoc

=== Cláudio Luís Marques Sampaio
Rua Benedito da Silva 291 +
Residencial Terra Nova, Campinas, SP +
CEP 13082-694 +
+55 (19) 3289-0644 +
+55 (19) 99116-3949 +
Casado, sem filhos +
Nacionalidades: *brasileiro* e *português* (com documentos e passaportes atualizados de ambas) +

Microempresa: MakerLinux S/A +
CNPJ 21.004.886/0001-11 +
Inscrição Municipal 00311816-9

mailto:patola@gmail.com[email pessoal] +
mailto:patola@makerlinux.com.br[email profissional] +
https://github.com/Patola[github] +
https://linkedin.com/in/patola[linkedin] +
http://buscatextual.cnpq.br/buscatextual/visualizacv.do?id=K4763932Z5[lattes]

{version-en-us}[versão em inglês deste documento]

[[summary]]
==== Sumário
* **Administrador de sistemas** e **desenvolvedor** graduado em **engenharia** com décadas de experiência em sistemas UNIX e Linux com clientes grandes e ambientes de missão crítica, com prática nos escopos de servidores, desktops, dispositivos móveis e dispositivos embarcados.
* Generalista de linguagens de programação com experiência (aplicações completas) em C, C++, Java, perl, python, SQL, php e shell scripting.
* Bom conhecimento em **sistemas de controle de versão** como **git**, Subversion (SVN), RCS, CVS, Bazaar.
* Bom conhecimento em **virtualização com contêineres** (docker, vagrant), **gerenciamento de configuração** (puppet, ansible), **nuvem** (softlayer, AWS), com experiência positiva mas limitada com orquestração (kubernetes, docker swarm).
* Experiência em programação com o uso de várias bibliotecas, frameworks e pacotes como libcurl, berkeley db, sqlite3, **redis**, rabbitmq, scrapy, gettext (para internacionalização), mysql, postgresql, oracle, MS SQL Server.
* Conhecimento profundo de licenças, filosofia e legislação **open source**, ativo contribuidor de alguns projetos.
* Conhecimento e experiência em empacotamento de aplicações de software em formatos como deb, rpm, lpp (AIX), AppImage e snap.
* Bom conhecimento de **eletrônica e circuitos** e profundo conhecimento e compreensão de **Impressão 3D** de baixo custo, com um https://github.com/Patola/ebook[livro] open-source popular publicado sobre este assunto. Por causa disto tem também boa experiência de modelagem com softwares open source como Blender, FreeCAD e OpenSCAD.
* **Palestrante e Conferencista** em variados http://buscatextual.cnpq.br/buscatextual/visualizacv.do?id=K4763932Z5[eventos e congressos importantes] e ainda **educador de youtube** com canais Maker/de Impressão 3D em https://www.youtube.com/makerlinux[português] and https://www.youtube.com/channel/UC65ISAck97KwTJRlFHEvTOg[inglês].

[[objective]]
==== Objetivo
* Devido ao meu conjunto diverso de competências, meu melhor desempenho é em **projetos de médio e longo prazo com altos riscos**, responsabilidades e circunstâncias imprevistas em ambientes DevOps.
* Trabalho bem em **ambientes de sistemas complexos** com linguagens múltiplas, conseguindo aprender e programar em uma nova em muito pouco tempo. Tenho alta habilidades em achar a causa-raiz de problemas e consertá-los em tempo de modo a manter o ambiente funcionando mesmo em emergências.
* Com a experiência em educação, também tenho bastante habilidade em **documentar e organizar** tais ambientes.
* Posso administrar diversos **ambientes de sistema Unix** incluindo planejar para alta disponibilidade (certificado em HACMP para AIX e com experiência em outros sistemas de HA) e topologia de redes/firewalls.
* Posso **desenvolver aplicações** que complementam um ambiente diverso, com linguagens de scripting, compiladas ou baseadas em VM.
* Posso fazer consultoria de estratégia e licenças open-source.
* Posso usar minhas aptidões extras para complementar o trabalho cotidiano, como modelar e imprimir cases para dispostivos embarcados.
* Trabalhei 5 anos no turno da madrugada, portanto se necessário posso trabalhar em horários diferentes.

[[education]]
==== Educação
* Universidade Estadual de Campinas (Unicamp), 2001. Engenharia de Computação
* Universidade Estadual de Campinas (Unicamp), 2010. Mestre em Biologia Molecular e Genética.
* Diversas certificações relacionadas a Unix:
** Certificação SAIR Linux, 2001
** Certificação múltipla CATE (Certified Advanced Technical Expert) de AIX, 2001.
** Certificações de administração de sistema em HP-UX e Solaris.
* Muitas certificações de trabalho e cursos internos, de **ITIL v3** a **Lotus Notes** e **Maximo**.
* Cursos de desenvolvimento embarcado com a __Techtraining__ (agora extinta) e __Embedded Labworks__.

[[experience]]
==== Experiência
* *Solvo* S/A, 1998-2002: administrador de sistemas Unix, 2001-2002: Desenvolvedor de Aplicações Unix.
* *YMF* S/A, 2002-2003: desenvolvedor J2EE para sistemas bancários.
* **Convergys, Inc.**, 2003-2005: desenvolvedor de aplicações Unix e Windows (front-end and backend)
* **IBM Brasil S/A**, 2005-2016: Administrador de sistemas Unix, Unix Team Lead, Desenvolvedor de Aplicações Unix, Programador e Administrador de Nuvem.
* **MakerLinux S/A**, 2016-2018: Dono/CTO.
* **TSYS, Inc.**, Outubro de 2018 até hoje: C/C++ & PL/SQL Application Developer

[[languages]]
==== Languages
* **Inglês**: fluente (escrita, leitura), bom (pronúncia).
* **Português**: linguagem nativa.
* **Francês**: intermediário (leitura, pronúncia), básico (escrita)
* **Spanish**: intermediário (leitura, pronúncia), básico (escrita)
